package com.sengine.engine.resources

import com.sengine.engine.animation.Animation
import com.sengine.engine.core.AssetKind
import com.sengine.engine.core.Prop
import com.sengine.engine.json.JVal
import com.sengine.engine.json.Json
import com.sengine.engine.json.jobj
import com.sengine.engine.particles.ParticleSpec
import com.sengine.engine.project.Project
import com.sengine.engine.render.BlendKind
import com.sengine.engine.tilemap.TileSet
import java.io.File

/**
 * Import metadata written next to every asset (`.<name>.meta.json`).
 * Generated by the import pipeline, editable in the asset browser, used by the sprite editor.
 */
class AssetMeta(var name: String) {
    var imported = System.currentTimeMillis()
    var kind = ""
    var width = 0
    var height = 0
    var pivotX = 0.5f
    var pivotY = 0.5f
    var pixelsPerUnit = 100f
    var nearest = false
    var slices = ArrayList<IntArray>()   // x, y, w, h
    var columns = 0
    var rows = 0
    var tileWidth = 0
    var tileHeight = 0
    var loopPointMs = 0
    var tags = ""
    var favorite = false

    fun toJson(): JVal.Obj {
        val o = JVal.Obj()
        o.put("name", name)
        o.put("imported", imported)
        o.put("kind", kind)
        o.put("size", com.sengine.engine.json.jarr(width, height))
        o.put("pivot", com.sengine.engine.json.jarr(pivotX, pivotY))
        o.put("pixelsPerUnit", pixelsPerUnit)
        o.put("nearest", nearest)
        if (slices.isNotEmpty()) {
            o.put("slices", JVal.Arr().also { a -> slices.forEach { s -> a.add(com.sengine.engine.json.jarr(s[0], s[1], s[2], s[3])) } })
        }
        if (columns > 0) o.put("columns", columns)
        if (rows > 0) o.put("rows", rows)
        if (tileWidth > 0) o.put("tileWidth", tileWidth)
        if (tileHeight > 0) o.put("tileHeight", tileHeight)
        if (loopPointMs > 0) o.put("loopPoint", loopPointMs)
        if (tags.isNotEmpty()) o.put("tags", tags)
        if (favorite) o.put("favorite", true)
        return o
    }

    fun fromJson(o: JVal.Obj) {
        name = o.str("name", name)
        imported = o.l("imported", imported)
        kind = o.str("kind")
        val size = o.floats("size")
        if (size.size >= 2) { width = size[0].toInt(); height = size[1].toInt() }
        val p = o.floats("pivot")
        if (p.size >= 2) { pivotX = p[0]; pivotY = p[1] }
        pixelsPerUnit = o.f("pixelsPerUnit", 100f)
        nearest = o.bool("nearest")
        slices.clear()
        o.arr("slices").forEach { s ->
            val a = (s as? JVal.Arr) ?: return@forEach
            slices.add(intArrayOf(
                (a.getOrNull(0) as? JVal.Num)?.v?.toInt() ?: 0,
                (a.getOrNull(1) as? JVal.Num)?.v?.toInt() ?: 0,
                (a.getOrNull(2) as? JVal.Num)?.v?.toInt() ?: 0,
                (a.getOrNull(3) as? JVal.Num)?.v?.toInt() ?: 0
            ))
        }
        columns = o.i("columns"); rows = o.i("rows")
        tileWidth = o.i("tileWidth"); tileHeight = o.i("tileHeight")
        loopPointMs = o.i("loopPoint")
        tags = o.str("tags")
        favorite = o.bool("favorite")
    }
}

/** Texture dimensions reported by the platform image loader. */
class TextureInfo(val width: Int, val height: Int)

/**
 * A 2D material: fragment shader source + uniforms + blend mode.
 * Used by [com.sengine.engine.core.Sprite2D] through its `material` property, and edited by the
 * Shader editor (which writes `.material.json` files into the project assets).
 */
class Material(var name: String = "material") {
    var template = "default"
    var fragment: String = ShaderTemplates.DEFAULT
    var blend = BlendKind.ALPHA
    var uniforms = LinkedHashMap<String, Float>()
    var texture: String = ""

    fun toJson(): JVal.Obj {
        val o = JVal.Obj()
        o.put("format", FORMAT)
        o.put("version", 1)
        o.put("name", name)
        o.put("template", template)
        o.put("blend", blend)
        o.put("fragment", fragment)
        if (texture.isNotEmpty()) o.put("texture", texture)
        if (uniforms.isNotEmpty()) {
            val u = JVal.Obj()
            uniforms.forEach { (k, v) -> u.put(k, v) }
            o.put("uniforms", u)
        }
        return o
    }

    fun fromJson(o: JVal.Obj) {
        name = o.str("name", name)
        template = o.str("template", "default")
        blend = o.i("blend")
        val f = o.str("fragment")
        if (f.isNotBlank()) fragment = f
        texture = o.str("texture")
        uniforms.clear()
        (o["uniforms"] as? JVal.Obj)?.fields?.forEach { (k, v) -> uniforms[k] = (v as? JVal.Num)?.v?.toFloat() ?: 0f }
    }

    companion object {
        const val FORMAT = "sengine.material"
        fun fromJson(text: String) = Material().also { it.fromJson(Json.parseObject(text)) }
    }
}

/** Built-in 2D shader templates used by the Shader editor's "new material" flow. */
object ShaderTemplates {
    /** Standard sprite passthrough with tint + texture. */
    const val DEFAULT = """
precision mediump float;
varying vec2 vUV;
uniform sampler2D uTex;
uniform vec4 uColor;
uniform float uUseTex;
void main() {
  vec4 c = uColor;
  if (uUseTex > 0.5) c *= texture2D(uTex, vUV);
  gl_FragColor = c;
}
"""

    const val OUTLINE = """
precision mediump float;
varying vec2 vUV;
uniform sampler2D uTex;
uniform vec4 uColor;
uniform vec2 uTexel;
uniform float uWidth;
uniform vec4 uOutlineColor;
void main() {
  vec4 base = texture2D(uTex, vUV) * uColor;
  float a = 0.0;
  for (int i = 0; i < 8; i++) {
    float ang = float(i) * 0.785398;
    vec2 off = vec2(cos(ang), sin(ang)) * uTexel * uWidth;
    a = max(a, texture2D(uTex, vUV + off).a);
  }
  float edge = clamp(a - base.a, 0.0, 1.0);
  vec3 rgb = mix(base.rgb, uOutlineColor.rgb, edge);
  gl_FragColor = vec4(rgb, max(base.a, edge * uOutlineColor.a));
}
"""

    const val GLOW = """
precision mediump float;
varying vec2 vUV;
uniform sampler2D uTex;
uniform vec4 uColor;
uniform vec2 uTexel;
uniform float uStrength;
void main() {
  vec4 base = texture2D(uTex, vUV) * uColor;
  vec4 sum = vec4(0.0);
  for (int i = -3; i <= 3; i++) {
    for (int j = -3; j <= 3; j++) {
      vec2 off = vec2(float(i), float(j)) * uTexel;
      sum += texture2D(uTex, vUV + off);
    }
  }
  sum /= 49.0;
  vec3 glow = sum.rgb * uStrength;
  gl_FragColor = vec4(base.rgb + glow, max(base.a, sum.a * uStrength * 0.6));
}
"""

    const val DISSOLVE = """
precision mediump float;
varying vec2 vUV;
uniform sampler2D uTex;
uniform vec4 uColor;
uniform sampler2D uNoise;
uniform float uThreshold;
uniform float uEdge;
uniform vec4 uEdgeColor;
void main() {
  vec4 base = texture2D(uTex, vUV) * uColor;
  float n = texture2D(uNoise, vUV).r;
  if (n < uThreshold - uEdge) discard;
  float edge = smoothstep(uThreshold - uEdge, uThreshold, n);
  vec3 rgb = mix(uEdgeColor.rgb, base.rgb, edge);
  gl_FragColor = vec4(rgb, base.a);
}
"""

    const val GRAYSCALE = """
precision mediump float;
varying vec2 vUV;
uniform sampler2D uTex;
uniform vec4 uColor;
uniform float uAmount;
void main() {
  vec4 c = texture2D(uTex, vUV) * uColor;
  float g = dot(c.rgb, vec3(0.299, 0.587, 0.114));
  gl_FragColor = vec4(mix(c.rgb, vec3(g), uAmount), c.a);
}
"""

    const val PIXELATE = """
precision mediump float;
varying vec2 vUV;
uniform sampler2D uTex;
uniform vec4 uColor;
uniform vec2 uSize;
uniform float uPixels;
void main() {
  vec2 grid = max(uSize / max(uPixels, 1.0), vec2(1.0));
  vec2 uv = floor(vUV * grid) / grid;
  gl_FragColor = texture2D(uTex, uv) * uColor;
}
"""

    const val WAVE = """
precision mediump float;
varying vec2 vUV;
uniform sampler2D uTex;
uniform vec4 uColor;
uniform float uTime;
uniform float uAmplitude;
uniform float uFrequency;
void main() {
  vec2 uv = vUV;
  uv.x += sin(uv.y * uFrequency + uTime * 3.0) * uAmplitude;
  gl_FragColor = texture2D(uTex, uv) * uColor;
}
"""

    const val DISTORTION = """
precision mediump float;
varying vec2 vUV;
uniform sampler2D uTex;
uniform sampler2D uNoise;
uniform vec4 uColor;
uniform float uStrength;
uniform float uTime;
void main() {
  vec2 n = texture2D(uNoise, vUV + vec2(uTime * 0.05, 0.0)).rg * 2.0 - 1.0;
  vec2 uv = vUV + n * uStrength;
  gl_FragColor = texture2D(uTex, uv) * uColor;
}
"""

    const val FLASH = """
precision mediump float;
varying vec2 vUV;
uniform sampler2D uTex;
uniform vec4 uColor;
uniform vec4 uFlashColor;
uniform float uAmount;
void main() {
  vec4 c = texture2D(uTex, vUV) * uColor;
  gl_FragColor = vec4(mix(c.rgb, uFlashColor.rgb, uAmount * uFlashColor.a), c.a);
}
"""

    val ALL: List<Pair<String, String>> = listOf(
        "default" to DEFAULT,
        "outline" to OUTLINE,
        "glow" to GLOW,
        "dissolve" to DISSOLVE,
        "grayscale" to GRAYSCALE,
        "pixelate" to PIXELATE,
        "wave" to WAVE,
        "distortion" to DISTORTION,
        "flash" to FLASH
    )

    fun named(name: String): String = ALL.firstOrNull { it.first == name }?.second ?: DEFAULT

    fun displayName(name: String) = name.replaceFirstChar { it.uppercase() }
}

/**
 * Loads, caches and invalidates project resources.
 *
 * Every parsed resource (tileset, animation, material, particle preset, metadata) is cached by
 * file name and invalidated when the file changes on disk, so the editor and the running game see
 * edits immediately. Image decoding stays in the platform layer through [textureLoader].
 */
class ResourceManager(var project: Project) {
    private val tilesets = HashMap<String, Pair<Long, TileSet>>()
    private val animations = HashMap<String, Pair<Long, Animation>>()
    private val materials = HashMap<String, Pair<Long, Material>>()
    private val particles = HashMap<String, Pair<Long, ParticleSpec>>()
    private val metas = HashMap<String, Pair<Long, AssetMeta>>()
    private val textureInfo = HashMap<String, TextureInfo>()
    private var sceneCache = 0

    /** Platform hook: returns the pixel size of an image asset (Android decodes with BitmapFactory). */
    var textureLoader: ((String) -> TextureInfo?)? = null

    var nullTextures = 0
        private set

    /** Switch to another project (used when a project is opened/created). */
    fun bindProject(p: Project) {
        if (p === project) return
        project = p
        clear()
    }

    fun stamp(name: String): Long {
        val f: File = project.assetFile(name)
        return if (f.exists()) f.lastModified() else -1L
    }

    // ------------------------------------------------------------------ typed loaders
    fun tileset(name: String): TileSet? {
        if (name.isBlank()) return null
        val stamp = stamp(name)
        tilesets[name]?.let { if (it.first == stamp) return it.second }
        val text = project.readAsset(name) ?: return null
        val ts = runCatching { TileSet.fromJson(text) }.getOrNull() ?: return null
        tilesets[name] = stamp to ts
        return ts
    }

    fun animation(name: String): Animation? {
        if (name.isBlank()) return null
        val stamp = stamp(name)
        animations[name]?.let { if (it.first == stamp) return it.second }
        val text = project.readAsset(name) ?: return null
        val a = runCatching { Animation.fromJson(text) }.getOrNull() ?: return null
        animations[name] = stamp to a
        return a
    }

    fun material(name: String): Material? {
        if (name.isBlank()) return null
        val stamp = stamp(name)
        materials[name]?.let { if (it.first == stamp) return it.second }
        val text = project.readAsset(name) ?: return null
        val m = runCatching { Material.fromJson(text) }.getOrNull() ?: return null
        materials[name] = stamp to m
        return m
    }

    fun particlePreset(name: String): ParticleSpec? {
        if (name.isBlank()) return null
        val stamp = stamp(name)
        particles[name]?.let { if (it.first == stamp) return it.second }
        val text = project.readAsset(name) ?: return null
        val p = runCatching { ParticleSpec.fromJson(text) }.getOrNull() ?: return null
        particles[name] = stamp to p
        return p
    }

    fun meta(name: String): AssetMeta {
        val stamp = stamp(name)
        metas[name]?.let { if (it.first == stamp) return it.second }
        val obj = project.readMetadata(name)
        val m = AssetMeta(name)
        if (obj.isEmpty()) {
            // first import: detect the kind so the browser can filter right away
            m.kind = AssetKind.of(name)?.name ?: "OTHER"
        } else m.fromJson(obj)
        m.name = name
        metas[name] = stamp to m
        return m
    }

    fun saveMeta(name: String, meta: AssetMeta) {
        project.writeMetadata(name, meta.toJson())
        metas[name] = stamp(name) to meta
    }

    /** Pixel size of an image asset (cached; decoded through the platform loader). */
    fun textureSize(name: String): TextureInfo? {
        textureInfo[name]?.let { return it }
        val info = textureLoader?.invoke(name)
        if (info != null) textureInfo[name] = info else nullTextures++
        return info
    }

    fun setTextureSize(name: String, width: Int, height: Int) {
        textureInfo[name] = TextureInfo(width, height)
    }

    fun invalidate(name: String) {
        tilesets.remove(name)
        animations.remove(name)
        materials.remove(name)
        particles.remove(name)
        metas.remove(name)
        textureInfo.remove(name)
    }

    fun invalidateAllTextures() = textureInfo.clear()

    fun clear() {
        tilesets.clear()
        animations.clear()
        materials.clear()
        particles.clear()
        metas.clear()
        textureInfo.clear()
        sceneCache = 0
    }

    fun cachedCount() = tilesets.size + animations.size + materials.size + particles.size + metas.size + textureInfo.size

    /** Import a file (bytes) with metadata generated by the pipeline. */
    fun importAsset(fileName: String, bytes: ByteArray, nearest: Boolean = false): Pair<String, AssetMeta> {
        val name = project.importAsset(fileName, bytes)
        val meta = AssetMeta(name)
        meta.kind = AssetKind.of(name)?.name ?: "OTHER"
        meta.nearest = nearest
        val size = decodeSize(bytes)
        if (size != null) {
            meta.width = size[0]
            meta.height = size[1]
            if (meta.kind == AssetKind.TEXTURE.name) {
                meta.nearest = nearest || (size[0] <= 128 && size[1] <= 128)
                meta.pixelsPerUnit = if (meta.nearest) 16f else 100f
            }
        }
        saveMeta(name, meta)
        return name to meta
    }

    /** Minimal PNG/JPEG header reader so metadata is available before first decode. */
    fun decodeSize(bytes: ByteArray): IntArray? {
        if (bytes.size < 24) return null
        // PNG
        if (bytes[0] == 0x89.toByte() && bytes[1] == 'P'.code.toByte() && bytes[2] == 'N'.code.toByte() && bytes[3] == 'G'.code.toByte()) {
            val w = ((bytes[16].toInt() and 0xFF) shl 24) or ((bytes[17].toInt() and 0xFF) shl 16) or ((bytes[18].toInt() and 0xFF) shl 8) or (bytes[19].toInt() and 0xFF)
            val h = ((bytes[20].toInt() and 0xFF) shl 24) or ((bytes[21].toInt() and 0xFF) shl 16) or ((bytes[22].toInt() and 0xFF) shl 8) or (bytes[23].toInt() and 0xFF)
            return intArrayOf(w, h)
        }
        // JPEG: scan SOFn markers
        if (bytes[0] == 0xFF.toByte() && bytes[1] == 0xD8.toByte()) {
            var i = 2
            while (i + 9 < bytes.size) {
                if (bytes[i] != 0xFF.toByte()) { i++; continue }
                val marker = bytes[i + 1].toInt() and 0xFF
                if (marker in 0xC0..0xCF && marker != 0xC4 && marker != 0xC8 && marker != 0xCC) {
                    val h = ((bytes[i + 5].toInt() and 0xFF) shl 8) or (bytes[i + 6].toInt() and 0xFF)
                    val w = ((bytes[i + 7].toInt() and 0xFF) shl 8) or (bytes[i + 8].toInt() and 0xFF)
                    return intArrayOf(w, h)
                }
                val len = ((bytes[i + 2].toInt() and 0xFF) shl 8) or (bytes[i + 3].toInt() and 0xFF)
                i += 2 + len
            }
        }
        return null
    }

    /** Create a new resource of the given kind from a template, then return its asset name. */
    fun createAnimation(name: String): Animation {
        val clean = project.uniqueAssetName(if (name.endsWith(".anim.json")) name else "$name.anim.json")
        val a = Animation(clean.removeSuffix(".anim.json"))
        a.setKey("position.x", 0f, 0f)
        a.setKey("position.x", 1f, 0f)
        project.writeAsset(clean, Json.write(a.toJson()))
        invalidate(clean)
        return a
    }

    fun createTileSet(name: String, texture: String, tileW: Int, tileH: Int): TileSet {
        val clean = project.uniqueAssetName(if (name.endsWith(".tileset.json")) name else "$name.tileset.json")
        val set = TileSet(clean.removeSuffix(".tileset.json"))
        set.texture = texture
        set.tileWidth = tileW
        set.tileHeight = tileH
        project.writeAsset(clean, Json.write(set.toJson()))
        invalidate(clean)
        return set
    }

    fun createMaterial(name: String, template: String): Material {
        val clean = project.uniqueAssetName(if (name.endsWith(".material.json")) name else "$name.material.json")
        val m = Material(clean.removeSuffix(".material.json"))
        m.template = template
        m.fragment = ShaderTemplates.named(template)
        project.writeAsset(clean, Json.write(m.toJson()))
        invalidate(clean)
        return m
    }

    fun saveAnimation(name: String, animation: Animation): Boolean {
        val ok = project.writeAsset(name, Json.write(animation.toJson()))
        if (ok) invalidate(name)
        return ok
    }

    fun saveTileSet(name: String, set: TileSet): Boolean {
        val ok = project.writeAsset(name, Json.write(set.toJson()))
        if (ok) invalidate(name)
        return ok
    }

    fun saveMaterial(name: String, material: Material): Boolean {
        val ok = project.writeAsset(name, Json.write(material.toJson()))
        if (ok) invalidate(name)
        return ok
    }

    fun saveParticlePreset(name: String, spec: ParticleSpec): Boolean {
        val ok = project.writeAsset(name, Json.write(spec.toJson()))
        if (ok) invalidate(name)
        return ok
    }

    /** Favourites list stored in project settings (`custom.favorites`). */
    fun favorites(): Set<String> =
        project.settings.custom["favorites"]?.split('|')?.filter { it.isNotBlank() }?.toSet() ?: emptySet()

    fun toggleFavorite(name: String): Set<String> {
        val set = favorites().toMutableSet()
        if (!set.add(name)) set.remove(name)
        project.settings.custom["favorites"] = set.joinToString("|")
        project.saveMeta()
        return set
    }

    fun recentAssets(): List<String> =
        project.settings.custom["recentAssets"]?.split('|')?.filter { it.isNotBlank() && project.assetExists(it) } ?: emptyList()

    fun markRecentAsset(name: String) {
        val list = recentAssets().filter { it != name }.toMutableList()
        list.add(0, name)
        project.settings.custom["recentAssets"] = list.take(20).joinToString("|")
        project.saveMeta()
    }

    fun describe(name: String): String {
        val kind = AssetKind.of(name)
        val size = project.assetSize(name)
        val dims = textureSize(name)?.let { "${it.width}×${it.height} · " } ?: ""
        return "${dims}${formatSize(size)} · ${kind?.label ?: "File"}"
    }

    private fun formatSize(bytes: Long) = when {
        bytes < 1024 -> "$bytes B"
        bytes < 1024 * 1024 -> "%.1f KB".format(bytes / 1024f)
        else -> "%.1f MB".format(bytes / 1024f / 1024f)
    }
}
